<?php

namespace SmallAdsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

// do zabawy i testów na poxniej
//    public function findAllCategoriesWithActiveAds() {
//        $em = $this->getEntityManager();
//        $query = $em->createQuery('SELECT c FROM SmallAdsBundle:Category c '
//                . ' JOIN SmallAdsBundle:Ad a WHERE CURRENT_TIMESTAMP() < a.endDate GROUP BY c.id');
//
//        return $query->getResult();
//    }

} 