<?php

namespace SmallAdsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SmallAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmallAdRepository extends EntityRepository
{
}
